name: "PR_has_a_valid_issue"

description: "Checks for a valid Issue number linked with the PR"

inputs:
  prbody:
    description: "The body of the PR to search for related issues"
    required: true
    
  prurl:
    description: "URL of the Pull Request"
    required: true
    
outputs:
  valid:
    description: "code for a valid issue (0=Invalid, 1=Valid)"
    
runs:
  using: "docker"
  image: "Dockerfile"
