name: Greetings for All

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened,closed]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Create comment for issue
      if: github.event_name =='issues'
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{tojson(github.event.issue.number)}}
        body: |
            @${{ github.actor }} Welcome to Rotten-Scripts! Thanks for opening this Issue, This Will definitely Improve our Project.
            While we are having a look at this. Feel free to self-assign and start working on it.
            **Use `/assign` to self-assign this issue**.


    - name: Create comment for PR
      if: github.event_name == 'pull_request_target' && github.event.action == 'opened'
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{tojson(github.event.number)}}
        body: |
            @${{ github.actor }} Thank you for Opening  pull request. We will get back to you as soon as possible. Your patience is greatly appreciated! Thanks! 🥳.
            PS: Please double check that you linked the corresponding issue.
    - name: Create comment for Merging PR
      if: github.event_name == 'pull_request_target' && github.event.action == 'closed' && github.event.pull_request.merged == true
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{tojson(github.event.number)}}
        body: |
            @${{ github.event.pull_request.user.login }} Hurray, your PR got merged 🥳. Thanks a bunch. Feel free to take another Issue.           
