name: 'Label Actions'
on: 
  pull_request:
    types: labeled

jobs:
  add-score:
    runs-on: ubuntu-latest
    if: startsWith(github.event.label.name, 'user')
    steps:
      - run: |
          echo ${{ github.event.label.name }}
          SCORE=${{ github.event.label.name }}
          echo $SCORE
          curl --data "score=$SCORE" --request POST https://wocleaderboard-backend.herokuapp.com/updateLeaderBoard/
